PR1AD/urls.py
from django.contrib import admin
from datetime import datetime
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from App import views, form
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('home/', views.home, name='home'),
    path('', include('adwords.urls')),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('admin/', admin.site.urls),
    url(r'^iprestrict/', include('iprestrict.urls', namespace='iprestrict')),
    path('login/',
         LoginView.as_view
             (
             template_name='app/login.html',
             authentication_form=form.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Login',
                 'year': datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(
        template_name='app/logout.html',
        extra_context=
        {
            'title': 'Logout',
            'message': 'You have been logged out. See you soon again.',
            'year': datetime.now().year,
        }
    ),
         name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adwords/urls.py
from django.urls import path, re_path
from . import views

app_name = 'adwords'

urlpatterns = [
    path('approve_ads_models/<str:c_id>', views.approve_ads_models, name="approve_ads_models"),
    path('ads_model_details/<str:c_id>', views.ads_model_details, name="ads_model_details"),
    path('ads_model/reports/<str:c_id>', views.reports, name="reports"),
    path('ads_model/delete/<str:c_id>', views.delete_ads_models, name="delete_ads_model"),
    path('ads_model/enable/<str:c_id>', views.enable, name="enable_ads_model"),
    path('ads_model/pause/<str:c_id>', views.pause_ads_models, name="pause_ads_model"),
    path('ads_model/edit/<str:c_id>', views.edit_ads_models, name="edit_ads_model"),
    path('ads_model/create/', views.Create_ads_models.as_view(), name="create_ads_model"),
    path('ads_models/', views.all_ads_models, name="all_ads_models"),
    path('', views.index, name='index'),
]

adwords/models.py
from django.db import models
import uuid

class restriction(models.Model):
    terms_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

class block_channels(models.Model):
    i_id = models.ForeignKey(restriction, on_delete=models.CASCADE)
    block_channels = models.CharField(max_length=100)

class whitelist_channels(models.Model):
    i_id = models.ForeignKey(restriction, on_delete=models.CASCADE)
    whitelist_channels = models.CharField(max_length=100)

class banned_keywords(models.Model):
    i_id = models.ForeignKey(restriction, on_delete=models.CASCADE)
    banned_keywords = models.CharField(max_length=100)

class ads_percentage(models.Model):
    i_id = models.ForeignKey(restriction, on_delete=models.CASCADE)
    ads_percentage = models.IntegerField()

import datetime
class ads_model(models.Model):
    model_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_by = models.CharField(max_length=200)
    ad_group_name = models.CharField(max_length=200)
    demographics = models.CharField(max_length=200)
    audiences = models.CharField(max_length=200)
    keywords = models.CharField(max_length=1000)
    topics = models.CharField(max_length=1000)
    placements = models.CharField(max_length=1000)
    cpv_bid = models.IntegerField(default=0, null=True)
    url = models.CharField(max_length=1000)
    ads_format = models.CharField(max_length=100)
    approved = models.IntegerField(default=0)
    pause = models.IntegerField(default=0)
    update_pending = models.IntegerField(default=0)

    def __str__(self):
        return self.ad_group_name

class ads_report(models.Model):
    link = models.OneToOneField(ads_model, primary_key=True, on_delete=models.CASCADE)
    cpm = models.IntegerField(default=0)
    cpv = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)

adwords/views.py
from django.shortcuts import render, HttpResponse, redirect
import argparse
from .get_client import get_client
from google_auth_oauthlib.flow import InstalledAppFlow
import argparse
import datetime
import sys
import uuid
import google.ads.google_ads.client
from adwords import models
from django.conf import settings
import os
from django.views.generic import View
from django.core.exceptions import ObjectDoesNotExist
import datetime

from adwords.authenticate import authenticate
from adwords.ads_report import ads_report
from adwords.get_campaign import get_campaign

from django.views.decorators.clickjacking import xframe_options_exempt
import uuid
from googleads import adwords
GOOGLE_RECAPTCHA_SECRET_KEY = 'private-key'

_DATE_FORMAT = '%Y%m%d'
# from .get_campaign import get_campaign
# get_campaign()

def index(request):
    user = request.user.username
    m = models.ads_model.objects.filter(created_by=user)
    if m:
        return render(request, 'index.html', {'ads_models': m})
    else:
        return render(request, 'index.html')

@xframe_options_exempt
def ads_model_details(request, c_id):
    try:
        ads_model_details = models.ads_model.objects.get(pk=c_id)
        return render(request, 'ads_model_details.html', {'c': ads_model_details})
    except ObjectDoesNotExist:
        error = "This ads_model Does Not Exists"
        return render(request, 'ads_model_details.html', {'e': error})    

def approve_ads_models(request, c_id):
    try:
        m = models.ads_model.objects.get(model_id=c_id)
        if m.update_pending == 1:
            m.update_pending = 0
            m.pause = 0
            m.approved = 1
        else:
            m.approved = 1
            m.pause = 0
        m.save()
        return ads_model_details(request, c_id)
    except (ObjectDoesNotExist, EOFError):
        error = "Some Unknown Error Occured"
        return render(request, 'ads_model_details.html', {'e': error})

def enable(request, c_id):
    try:
        m = models.ads_model.objects.get(model_id=c_id)
        m.pause = 0
        m.approved = 1
        m.save()
        return ads_model_details(request, c_id)
    except ObjectDoesNotExist:
        error = "This ads_model Does Not Exists"
        return render(request, 'ads_model_details.html', {'e': error})    

def all_ads_models(request):
    m = models.ads_model.objects.all()
    if m:
        data = {
            'ads_models': m
        }
        return render(request, 'ads_models.html', data)
    else:
        return render(request, 'ads_models.html')


def reports(request, c_id):
    r = ads_report(c_id)
    data = {
        'cpm': r.cpm,
        'cpv': r.cpv,
        'cost': r.cost
    }
    return render(request, 'reports.html', data)

def pause_ads_models(request, c_id):
    m = models.ads_model.objects.get(model_id=c_id)
    m.pause = 1
    m.approved = 0
    m.save()
    return ads_model_details(request, c_id)

def delete_ads_models(request, c_id):
    c = models.ads_model.objects.get(model_id=c_id)
    c.delete()
    return redirect("adwords:all_campaigns")

def edit_ads_models(request, c_id):
    return render(request, 'index.html', {'model': c_id})


class Create_ads_models(View):
    def post(self, *args, **kwargs):
        user = self.request.user.username
        model_id = self.request.POST['model_id'] or None
        ad_name = self.request.POST['ad_name']
        keywords = self.request.POST['keywords']
        cpv_bid = self.request.POST.get('cpv_bid')
        video_url = self.request.POST['video_url']
        instream_ads = self.request.POST['instream']
        discovery_ads = self.request.POST['discovery']  

        # recaptcha_response = request.POST['g-recaptcha-response']

        # url = 'https://www.google.com/recaptcha/api/siteverify'
        # payload = {
        #     'secret': GOOGLE_RECAPTCHA_SECRET_KEY,
        #     'response': recaptcha_response
        # }
        # data = urllib.parse.urlencode(payload).encode()
        # req = urllib.request.Request(url, data=data)
        # response = urllib.request.urlopen(req)
        # result = json.loads(response.read().decode())

        # if (not result['success']) or (not result['action'] == 'create'):
        #     return HttpResponse("error-captcha")
        
        blocked = models.block_channels.objects.filter(block_channels=video_url)
        if blocked:
            return HttpResponse("error-blocklist")

        whitelisted = models.whitelist_channels.objects.filter(whitelist_channels=video_url)
        if whitelisted:
            pass
        else:
            return HttpResponse("error-whitelist")

        if keywords != '':
            keyword = keywords.split(',')
            for i in keyword:
                k = models.banned_keywords.objects.filter(banned_keywords=i)
                if k:
                    return HttpResponse("error-keywords")
        
        ads_format = ''

        if instream_ads == 1:
            ads_format = 'instream_ads'
        else:
            ads_format = 'discovery_ads'

        if model_id is not None:
            m = models.ads_model.objects.get(model_id=model_id)
            m.created_by = user
            m.ad_group_name = ad_name
            m.demographics = 'All'
            m.audiences = 'All'
            m.keywords = keywords
            m.topics = 'All'
            m.placements = 'All'
            m.cpv_bid = cpv_bid
            m.url = video_url
            m.ads_format = ads_format
            m.approved=0
            m.pause=0
            m.update_pending = 1
            m.save()
        else:
            m = models.ads_model.objects.create(
                created_by = user,
                ad_group_name = ad_name,
                demographics = 'All',
                audiences = 'All',
                keywords = keywords,
                topics = 'All',
                placements = 'All',
                cpv_bid = cpv_bid,
                url = video_url,
                ads_format = ads_format
            )
            m.save()
            models.ads_report.objects.create(link=m)
        return HttpResponse("Your Applicaiton submitted")

adwords/templates/ads_model_details.html
{% load static %}
<html>
    <head>
        <title>PR1AD</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu&family=Dancing+Script:wght@300&display=swap" rel="stylesheet">
        <style>
            a:hover{
                text-decoration: none;
            }
            body{
                background: white;
                font-family: 'Ubuntu' !important;
                width: 100%;
                height: 100%;
            }
            .nav-item, a{
                font-weight: bolder;
                padding: 10px 30px 10px 30px;   
            }
            .nav-item, a:hover{
                transition: ease 0.5s;
                color: rgb(0, 0, 0) !important;
            }
            .text-white{
                color: white;
            }
            .text-black{
                color: black;
            }
            @media(max-width: 790px){
                .head1{
                    font-size: 3rem !important;
                }
                .hr-mobile{
                    display: none;
                }
                .navbar-brand{
                    display: block;
                }
                .data_field{
                    border: none !important;
                }
                .navbar-collapse{
                    background-color: darkviolet ;
                    border-radius: 0px 10px 0px 10px;
                }
                .header_part{
                    background-size: 220rem !important;
                    background-position: bottom  !important;
                    padding-top: 40px !important;
                }
                .nav-item{
                    border-bottom: 1.5px solid rgb(255, 255, 255);
                }
            }
            
            table, td{
                width: 100px;
                border: none !important;
            }
            html{
                scroll-behavior: smooth;
            }
        </style>
    </head>
    <style>
        .select1:hover{
            transition: ease 1s;
            border: none !important;
            background-color: rgb(241, 241, 241);
        }
        .select2:hover{
            transition: ease 1s;
            border: none !important;
            background-color: rgb(241, 241, 241);
        }
        a:hover{
            text-decoration: none;
        }
    </style>
    <body>
        <nav class="col-md-12 navbar navbar-expand-lg" style="background: blue; z-index: 2000;">
            <button class="navbar-toggler" type="button" style="border: none; outline: none;" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <!-- <span class="navbar-toggler-icon"></span> -->
              <i style="color: white; padding-top: 5px;" class="fas fa-bars"></i>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mx-auto text-center">
                <li class="nav-item">
                  <a style="color: white;" class="nav-link" href="{% url 'home' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link" href="{% url 'about' %}">COMPANY</a>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link" href="{% url 'contact' %}">CONTACT US</a>
                </li>
              </ul>
            </div>
        </nav><Br>
        <div class="container">
            <div class="mx-auto text-center" style="padding: 30px;">
                <h1><a style="font-weight: 500; color: black;" href="{% url 'home' %}">Ads Group Details</a></h1>
                <hr>
                {% if e %}
                    <p>{{ e }}</p>
                {% endif %}
                <div class="ads_models mr-auto text-left">
                    <div class="row">
                        <div class="table_responsive" style="width: 70%;">
                            <form class="form">
                                <table class="table">
                                    {% if c %}
                                    <tr>
                                        <td><p>Ad Group Name :</p></td>
                                        <td><b><time>{{ c.ad_group_name }}</time></b></td>
                                    </tr>
                                    <tr>
                                        <td><p>Keywords :</p></td>
                                        <td><b><time>{{ c.keywords }}</time></b></td>
                                    </tr>
                                    <tr>
                                        <td><p>CPV Bid :</p></td>
                                        <td><b><time>{{ c.cpv_bid }}</time></b></td>
                                    </tr>
                                    <tr>
                                        <td><p>Video URL :</p></td>
                                        <td><b><time>{{ c.url }}</time></b></td>
                                    </tr>
                                    <tr>
                                        <td><p>Ads Format :</p></td>
                                        <td><b><time>{{ c.ads_format }}</time></b></td>
                                    </tr>
                                    <tr>
                                        <td><p>Status :</p></td>
                                        <td>
                                            {% if c.approved == 1 %}
                                                <b style="color: green;">Active</b>
                                            {% elif c.update_pending == 1 %}
                                                <b style="color: red;">Update In Progress</b>
                                            {% else %}
                                                <b style="color: red;">Not Active</b>
                                            {% endif %}
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
                    {% if user.is_superuser %}
                        {% if c.approved == 1 %}
                            
                        {% else %}
                        <button class="approved_btn btn btn-primary" style="color: white; font-weight: bolder;"><a>Approve</a></button>
                        {% endif %}
                        {% if c.pause == 1 %}
                            <button class="enable_btn btn btn-primary"><a style="text-decoration: none; color: white;" href="{% url 'adwords:enable_ads_model' c_id=c.model_id %}">Enable</a></button>
                        {% else %}
                            <button class="pause_btn btn btn-primary"><a style="text-decoration: none; color: white;" href="{% url 'adwords:pause_ads_model' c_id=c.model_id %}">Pause</a></button>
                        {% endif %}
                        <button class="delete_btn btn btn-primary"><a style="text-decoration: none; color: white;" href="{% url 'adwords:delete_ads_model' c_id=c.model_id  %}">Delete</a></button>
                        <button class="edit btn btn-primary"><a style="text-decoration: none; color: white;" href="{% url 'adwords:edit_ads_model' c_id=c.model_id %}">Edit</a></button>
                        <button class="edit btn btn-primary"><a style="text-decoration: none; color: white;" href="{% url 'adwords:reports' c_id=c.model_id %}">Reports</a></button>
                    {% else %}
                    <button class="edit btn btn-primary"><a style="text-decoration: none; color: white;" href="{% url 'adwords:edit_ads_model' c_id=c.model_id %}">Edit ads_model</a></button>
                    {% endif %}
                </div>
                <br><br><br>
            </div>
        </div>
    </body>
    <script>
        $('.approved_btn').click(function(){
            window.location.href ="{% url 'adwords:approve_ads_models' c_id=c.model_id %}"
        });
    </script>
    <div class="footer container mx-auto text-center" style="right: 0; left: 0; bottom: 0; position: relative;">
        <hr>
        <p>Copyright  &copy;  2020 PR1AD.com | Powered by Perfection</p>
     </div>
    {% endif %}
</html>

adwords/templates/ads_models.html
{% load static %}
<html>
    <head>
        <title>PR1AD</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu&family=Dancing+Script:wght@300&display=swap" rel="stylesheet">
        <style>
            a{
                text-decoration: none;
            }
            a:hover{
                text-decoration: none;
            }
            body{
                background: white;
                font-family: 'Ubuntu' !important;
                width: 100%;
                height: 100%;
            }
            .nav-item, a{
                font-weight: bolder;
                padding: 10px 30px 10px 30px;  
            }
            .nav-item, a:hover{
                transition: ease 0.5s;
                color: rgb(0, 0, 0) !important;
            }
            .text-white{
                color: white;
            }
            .text-black{
                color: black;
            }
            @media(max-width: 790px){
                .head1{
                    font-size: 3rem !important;
                }
                .hr-mobile{
                    display: none;
                }
                .navbar-brand{
                    display: block;
                }
                .data_field{
                    border: none !important;
                }
                .navbar-collapse{
                    background-color: darkviolet ;
                    border-radius: 0px 10px 0px 10px;
                }
                .header_part{
                    background-size: 220rem !important;
                    background-position: bottom  !important;
                    padding-top: 40px !important;
                }
                .nav-item{
                    border-bottom: 1.5px solid rgb(255, 255, 255);
                }
            }
            
            table, td{
                width: 100px;
                border: none !important;
            }
            html{
                scroll-behavior: smooth;
            }
        </style>
    </head>
    <body>
        <nav class="col-md-12 navbar navbar-expand-lg" style="background: blue; z-index: 2000;">
            <button class="navbar-toggler" type="button" style="border: none; outline: none;" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <!-- <span class="navbar-toggler-icon"></span> -->
              <i style="color: white; padding-top: 5px;" class="fas fa-bars"></i>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mx-auto text-center">
                <li class="nav-item">
                  <a style="color: white;" class="nav-link" href="{% url 'home' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link" href="{% url 'about' %}">COMPANY</a>
                </li>
                <li class="nav-item">
                    <a style="color: white;" class="nav-link" href="{% url 'contact' %}">CONTACT US</a>
                </li>
              </ul>
            </div>
        </nav><Br>
        <div class="container">
            <div class="mx-auto text-center" style="padding: 30px;">
                <h1><a style="font-weight: 500; color: black;" href="{% url 'home' %}">Adword Panel</a></h1>
                <hr><Br>
                <div class="ads_models mr-auto text-left">
                    <div class="mr-auto text-left container">
                        {% if ads_models %}
                            <h4>ads_models - Pending</h4>
                            {% for c in ads_models %}
                                {% if c.pause != 1 %}
                                    {% if c.approved == 0 %}
                                        <div style="margin: 5px;"><a href="{% url 'adwords:ads_model_details' c_id=c.model_id %}">{{ c.ad_group_name }}</a></div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <p>No Pending ads_models</p>
                        {% endif %}
                    </div>
                    <div class="mr-auto text-left container">
                        {% if ads_models %}
                            <Br><h4>ads_models - Running</h4>
                            {% for c in ads_models %}
                                {% ifequal 1 c.approved %}
                                <div style="margin: 5px;"><a href="{% url 'adwords:ads_model_details' c_id=c.model_id %}">{{ c.ad_group_name }}</a></div>
                                {% endifequal %}
                            {% endfor %}
                        {% else %}
                            <p>No Running ads_models</p>
                        {% endif %}
                    </div>
                    <div class="mr-auto text-left container">
                        {% if ads_models %}
                            <Br><h4>ads_models - Paused</h4>
                            {% for c in ads_models %}
                                {% ifequal 1 c.pause %} 
                                <div style="margin: 5px;"><a href="{% url 'adwords:ads_model_details' c_id=c.model_id %}">{{ c.ad_group_name }}</a></div>
                                {% endifequal %}
                            {% endfor %}
                        {% else %}
                            <p>No Paused ads_models</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <div class="footer container mx-auto text-center" style="right: 0; left: 0; bottom: 0; position: relative;">
            <hr>
            <p>Copyright  &copy;  2020 PR1AD.com | Powered by Perfection</p>
         </div>
    </body>
</html>