PR1AD/urls.py
from django.contrib import admin
from datetime import datetime
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from App import views, form
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('home/', views.home, name='home'),
    path('', include('adwords.urls')),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('admin/', admin.site.urls),
    url(r'^iprestrict/', include('iprestrict.urls', namespace='iprestrict')),
    path('login/',
         LoginView.as_view
             (
             template_name='app/login.html',
             authentication_form=form.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Login',
                 'year': datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(
        template_name='app/logout.html',
        extra_context=
        {
            'title': 'Logout',
            'message': 'You have been logged out. See you soon again.',
            'year': datetime.now().year,
        }
    ),
         name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adwords/urls.py
from django.urls import path, re_path
from . import views

app_name = 'adwords'

urlpatterns = [
    path('approve_ads_models/<str:c_id>', views.approve_ads_models, name="approve_ads_models"),
    path('ads_model_details/<str:c_id>', views.ads_model_details, name="ads_model_details"),
    path('ads_model/reports/<str:c_id>', views.reports, name="reports"),
    path('ads_model/delete/<str:c_id>', views.delete_ads_models, name="delete_ads_model"),
    path('ads_model/enable/<str:c_id>', views.enable, name="enable_ads_model"),
    path('ads_model/pause/<str:c_id>', views.pause_ads_models, name="pause_ads_model"),
    path('ads_model/edit/<str:c_id>', views.edit_ads_models, name="edit_ads_model"),
    path('ads_model/create/', views.Create_ads_models.as_view(), name="create_ads_model"),
    path('ads_models/', views.all_ads_models, name="all_ads_models"),
    path('', views.index, name='index'),
]

App/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>





<p>Use this area to provide additional information.</p>

{% endblock %}

App/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    India Shubham<br />
    Lucknow<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@PR1AD.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@PR1AD.com</a>
</address>

{% endblock %}

App/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="row" style="margin-top:20px;">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" style="">

      <div class="item active" style=" height: 300px!important;">
          <a href="{{ home_url1 }}"><img src="/media/{{ homeimage_link1 }}" alt="Los Angeles" style="width:100%;"></a>
        <div class="carousel-caption" style="background-color:{{ background_color }};opacity:0.6;position:absolute;
                left:5%;width:20%">
          <a href="{{ home_url1 }}" style="text-decoration:none">
              <p style="color:{{ font_color }}">{{ home_text1 }}</p>
          </a>
        </div>
      </div>

      <div class="item" style=" height: 300px!important;">
          <a href="{{ home_url2 }}"><img src="/media/{{ homeimage_link2 }}" alt="Chicago" style="width:100%;"></a>
        <div class="carousel-caption" style="background-color:{{ background_color }};opacity:0.6;position:absolute;
                left:5%;width:20%">
          <a href="{{ home_url2 }}" style="text-decoration:none">
              <p style="color:{{ font_color }}">{{ home_text2 }}</p>
          </a>
        </div>
      </div>

      <div class="item" style=" height: 300px!important;">
        <a href="{{ home_url3 }}"><img src="/media/{{ homeimage_link3 }}" alt="New York" style="width:100%;"></a>
        <div class="carousel-caption" style="background-color:{{ background_color }};opacity:0.6;position:absolute;
                left:5%;width:20%">
          <a href="{{ home_url3 }}" style="text-decoration:none">
              <p style="color:{{ font_color }}">{{ home_text3 }}</p>
          </a>
        </div>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Study ShubHam ADS WEB</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-primary btn-large" href="https://djangobook.com/django-tutorials/">Yes, give me the latest tables right away &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get updated and analyze the upcoming ADS</h2>
        <p>
            The Python Package Index is a repository of software for the Python programming language.
            Together with Django, it offers a tremendous platform for web site development
        </p>
        <p><a class="btn btn-primary btn-large" href="https://pypi.org/">I can't wait to get into the details &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Use our ads campagin or build your own</h2>
        <p>You can easily publish to Microsoft Azure using Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-primary btn-large" href="http://azure.microsoft.com">Waou, that would be awesome! &raquo;</a></p>
    </div>
</div>

{% endblock %}

App/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - </title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
{#    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap-grid.min.css' %}" />#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap-reboot.min.css' %}" />#}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/dc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/custom.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/navbar.css' %}" />
{#    <link rel="stylesheet" type="text/css" href="{% static 'app/content/about-style.css' %}" />#}
    <script src="{% static 'app/scripts/jquery.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.min.js' %}"></script>


</head>

<body>
    <form method="POST" action="http://djangoserver" style="display: none" >{% csrf_token %}</form>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand" style="font-size: 34px">
                    <div class="logo-container">
{#                        <img src="/media/logo/logo.png" class="logo">#}
                    </div>
                    PR1AD.com
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <div class="navbar-right">
                    <ul class="nav navbar-nav" style="font-size: 16px">
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'about' %}">Company</a></li>
                        {% if user.is_superuser %}
                            <li><a href="{% url 'adwords:all_ads_models' %}">Adwords Panel</a></li>
                        {% elif user.is_authenticated %}
                            
                        {% endif %}
                        {% if user.is_authenticated %} 
                        <li><a href="{% url 'adwords:index' %}">Dashboard</a></li>
                        {% endif %}
                        <li><a href="{% url 'contact' %}">Contact Us</a></li>
{#                        <li class="dropdown">#}
{#                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#                                About <b class="caret"></b>#}
{#                            </a>#}
{#                            <ul class="dropdown-menu">#}
{#                                #}
{#                            </ul>#}
{#                        </li>#}
                    </ul>

                    {% include 'app/loginpartial.html' %}
                </div>


            </div>
        </div>
    </div>

</div>


    <div class="container body-content">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %} {% endblock %}

     <hr>
     <div class="footer">
        <p>Copyright  &copy;  {{ year }}-2021 &emsp; by PR1AD.com &emsp; | &emsp; &#9829;  Proudly powered by India Shubham   &#9829; &emsp;  |  &emsp;   reg.no. *******</p>
     </div>

    </div>

</body>
</html>

App/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h3>Enter your credentials to login</h3>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="login-btn btn btn-default" />
                    </div>
                </div>
                <div class="border-top pt-3">
                    <small class="text-muted">
{#                        Need an account? <a class="ml-2" href="{% url 'register' %}">Register</a>#}
                    </small>
                </div>
                {% if form.errors %}
                <script>
                    $(document).ready(function(){
                        if(!!$.cookie('value')){
                            var c = parseInt($.cookie('value'));
                            if ( c === 4 ){
                                var username = $('#id_username').val();
                                $.cookie("username", username);
                                var date = new Date();
                                var minutes = 30;
                                date.setTime(date.getTime() + (minutes * 60 * 1000));
                                $.cookie("acc_locked", c, { expires: date });
                                $('.id_locked').fadeIn();
                                $('.validation-summary-errors').hide();
                                $('.login-btn').prop("disabled", true);
                            }
                            else{
                                console.log("out"+c);
                                $.cookie('value', parseInt(c)+1);    
                            }
                        }
                        else{
                            $.cookie('value', 1);
                        }
                    });
                </script>
                <div class="id_locked" style="display: none;">
                    <p style="color: red; font-weight: bolder;" class="validation-summary-errors2">You're ID has been locked for 30 mins. Try Again Later...</p>
                </div>
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>

    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>
<script>
    $('#id_password').change(function(){
        var username = $('#id_username').val();
        if (username === $.cookie('username')){
            $('.login-btn').prop("disabled", true);
        }
        else{
            $('.login-btn').prop("disabled", false);
        }
    });
    $(document).ready(function(){
        if(!!$.cookie('acc_locked')){
            $('.login-btn').prop("disabled", true);
        }
        else{
            $('.login-btn').prop("disabled", false);
        }
    });
</script>
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

App/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post">
    {% csrf_token %}
    <ul class="nav navbar-nav">
        <li><a class="nav navbar-brand" style="font-size: 14px">Welcome {{ user.profile.firstname }} [{{user.profile.user}}], stay in touch!</a></li>
        <li><a href="{% url 'profile' %}">Profile</a></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Logout</a></li>
    </ul>
</form>

{% else %}

<form>
    <ul class="nav navbar-nav">
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'register' %}">Register</a></li>
    </ul>
</form>

{% endif %}

App/templates/app/logout.html
{% extends "app/layout.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{% url 'login' %}">Log in again</a>
        </small>
    </div>

{% endblock content%}

App/templates/app/profile.html
{% extends "app/layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% load static %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>


<div class="content-section">
    <form method="POST" action={% url 'profile' %} enctype="multipart/form-data">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile info</legend>
            {% crispy u_form %}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </fieldset>
    </form>
</div>

{% endblock content%}

App/templates/app/register.html
{% extends "app/layout.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<div class="content-section">
    <form method="POST" action={% url 'register' %}>
        <fieldset class="form-group">
            {% crispy form %}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </fieldset>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
</div>

{% endblock content%}

App/templates/app/tutorials.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}